### ISSUE TITLE
Fail if automake 1.13 is installed

### ISSUE THREAD

**Issue by JotaRandom** [kalgasnik/lightdm-another-gtk-greeter#1]
Log
´/usr/bin/gnome-autogen.sh
checking for autoconf >= 2.53...
  testing autoconf2.50... not found.
  testing autoconf... found 2.69
checking for automake >= 1.7...
  testing automake-1.12... not found.
  testing automake-1.11... not found.
  testing automake-1.10... not found.
  testing automake-1.9... not found.
  testing automake-1.8... not found.
  testing automake-1.7... not found.
**_Error**_: You must have automake >= 1.7 installed
  to build lightdm-another-gtk-greeter.  Download the appropriate package for
  from your distribution or get the source tarball at
    http://ftp.gnu.org/pub/gnu/automake/automake-1.7.tar.gz
´

but automake 1.13 is installed

**Comment by kalgasnik** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=690920
Temporary solution: downgrading to 1.12

**Comment by JotaRandom** [comment]
thanks

PD: is a thank in the good sense
