### ISSUE TITLE
Widgets no longer appear after upgrade

### ISSUE THREAD

**Issue by Generator** [kalgasnik/lightdm-another-gtk-greeter#5]
Widgets no longer appear after upgrade (1.0.5.0 -> 1.0.6.0) if a background is set

lightdm-another-gtk-greeter with background
![ldm_background](https://f.cloud.github.com/assets/44146/1298275/a7e2b90a-30f1-11e3-8c37-5840ff495985.png)

lightdm-another-gtk-greeter without background
![ldm_nobackground](https://f.cloud.github.com/assets/44146/1298282/b3088044-30f1-11e3-8caa-e7cbf016460f.png)

Background used http://i.imgur.com/ABP147d.png

**Comment by kalgasnik** [comment]
It's effect of updating Gtk to 3.10. As I can see there are some other bugs related to this update (missing panel icons).
